name: Docker images build

on:
  push:
    tags:
    - 'v*'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    environment: secure
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set app version
      run: V=${{ github.ref_name }} && VT="${V#v}" && sed "s@APP_VERSION@$VT@" misc/version.go.in > misc/version.go

    - name: Login to Registry Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta for migration
      id: meta-migration
      uses: docker/metadata-action@v4
      with:
        images: |
          nixyslab/nxs-support-bot-migrations

    - name: Docker meta for app
      id: meta-app
      uses: docker/metadata-action@v4
      with:
        images: |
          nixyslab/nxs-support-bot

    - name: Build and push migration
      uses: docker/build-push-action@v4
      with:
        context: .
        file: .docker/Dockerfile-migration
        push: true
        tags: ${{ steps.meta-migration.outputs.tags }}

    - name: Build and push app
      uses: docker/build-push-action@v4
      with:
        context: .
        file: .docker/Dockerfile
        push: true
        tags: ${{ steps.meta-app.outputs.tags }}
